# General Settings
title = "Cristian Medeiros - CTO as a Service"
baseURL = "https://cmxo.tech/" #YOUR SITE URL
languageCode = "en-us"
theme = "glacier"
resourceDir = "resources"
[pagination]
  pagerSize = 4
summaryLength = 50
DefaultContentLanguage = "pt-br" # Site language. Available translations in the theme's `/i18n` directory.

[markup.goldmark.renderer]
unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Menu Settings
[menu]
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = ""
  weight = 1
[[menu.main]]
  identifier = "sobre"
  name = "Sobre"
  url = "sobre/"
  weight = 2
[[menu.main]]
  identifier = "servicos"
  name = "Serviços"
  url = "servicos/"
  weight = 3  
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "blog/"
  weight = 4
[[menu.main]]
  identifier = "contact"
  name = "Contato"
  url = "contato/"
  weight = 5

# Main Settings
[params]
defaultLogo = "CM eXtended Office"
defaultKeywords = ["CTO as a Service", "Fractional CTO", "Interim CTO", "Consultor de desenvolvimento", "Consultor de tecnologia", "CTO Interino", "CTO Fracionado"]
defaultDescription = "Glacier - Clean & Minimal Portfolio Hugo Theme"
dateFormat = "January 2, 2006"
authorName = "Cristian Medeiros"
disqusComments = "" #YOUR DISQUS COMMENTS SHORTNAME
formspreeFormID = "xanpanww" #YOUR FORMSPREE FORM ID
reCAPTCHAKey = "6LdlkOorAAAAAGWrUvfVWG7Qm47hMecKE09B4ufW" #YOUR reCAPTCHA v2 key
googleMapsApiKey = "AIzaSyAV1KS10sb3O462XosfZTKohHJwi6C0joo" #YOUR GOOGLE API KEY
googleAnalytics = "G-96XSYJ5XYK"

# Sidebar Settings
[params.sidebar]
enable = 1 #SIDEBAR SHOW: [ 1 - yes, 0 - no ] For General page "Blog"
position = "right" #SIDEBAR POSITION: [ left, right ] For General page "Blog"
search = 1 #SIDEBAR SEARCH WIDGET: [ 1 - yes, 0 - no ]
latestPosts = 1 #SIDEBAR LATEST POSTS WIDGET: [ 1 - yes, 0 - no ]
categories = 0 #SIDEBAR CATEGORIES TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
tags = 0 #SIDEBAR TAG TAXONOMY WIDGET: [ 1 - yes, 0 - no ]


[params.about]
about = 0 #SIDEBAR ABOUT WIDGET: [ 1 - yes, 0 - no ]
image = "images/author-blog.jpg"
name = "John Smith"
text = "<p>Can't multiply. Set set created thing light blessed third without. Him can't kind called set is second thing from you'll tree. Seed darkness you. Itself night. Life. Hath creature good.</p>"
[[params.about.social]]
icon = "fa-brands fa-x-twitter"
url = "https://www.twitter.com/"
[[params.about.social]]
icon = "fa-brands fa-facebook"
url = "https://facebook.com/"
[[params.about.social]]
icon = "fa-brands fa-dribbble"
url = "https://dribbble.com/"
[[params.about.social]]
icon = "fa-brands fa-youtube"
url = "https://www.youtube.com/"

[params.subscribe]
subscribe = 0 #SIDEBAR SUBSCRIBE WIDGET: [ 1 - yes, 0 - no ]
mailChimpURL = "https://stevedogs.us9.list-manage.com/subscribe/post?u=df0aa2ea10f32337b29b342d4&id=41ddc569b4"  # Example MailChimp url: http://xxx.xxx.list-manage.com/subscribe/post?u=xxx&id=xxx

# Portfolio Settings (Filter)
[params.portfolio]
[[params.portfolio.filters]]
name = "Branding"
slug = "branding"
[[params.portfolio.filters]]
name = "Design"
slug = "design"
[[params.portfolio.filters]]
name = "Illustration"
slug = "illustration"

# Footer Settings
[params.footer]
copyright = "CM-XO © 2025."

# Social Settings
[[params.social]]
title = "Linkedin"
url = "https://www.linkedin.com/in/crisdevbr/"


# Sitemap Settings
[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
home = ["HTML", "RSS", "JSON"]